### ISSUE TITLE
The date displayed on the note is international time

### ISSUE THREAD

**Issue by SiriusXT** [dvai/Trilium-Heatmap#6]
When I checked the heat map, I found that the results were not displayed after being revised yesterday. When I checked the code, I found that utcDateCreated and utcDateModified were used. After I changed them to dateCreated and dateModified, it became normal. I feel like it would be more appropriate to use local time.

https://github.com/dvai/Trilium-Heatmap/blob/f551153cc9b4eb7d23f5d4fe4d20dac26a5aff75/Trilium-Heatmap/html/js.js#L50

**Comment by dvai** [comment]
You are correct, it has been fixed.
